"""empty message

Revision ID: 205ebe45d12f
Revises: 430aeec79a81
Create Date: 2020-05-21 14:00:25.379002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205ebe45d12f'
down_revision = '430aeec79a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'value')
    # ### end Alembic commands ###
